# Use a lightweight Node.js base image
FROM node:16.17.1-alpine

# Set the working directory
WORKDIR /app/backend

# copy the contents to tht dest
COPY . .

# Install dependencies
RUN npm install

ENV PORT=5000
# Expose the port your app runs on (e.g., 3000)
EXPOSE 5000

# Start the app
CMD ["node", "index.js"]